local allConvertedNames = {
    "Bogota Approach",
    "Los Angeles Center",
    "Online until appx 2300z",
    "SEA",
    "Havana Center",
    "Quito Torre",
    "Read our Letter to Airmen at bvartcc",
    "Atlanta Center",
    "SEQM ATIS INFORMATION D",
    "Arrivals from UMKAL expect the RNAV UMKAL5C Rwy 17R",
    "Seattle Center",
    "ATLANTA AIRPORT INFORMATION L",
    "Warszawa Approach",
    "Lima Control 128",
    "SPJC ATIS INFORMATION R",
    "Callsign",
    "ZOA",
    "LaGuardia Tower",
    "KLGA ATIS INFO C 2151Z",
    "JAX",
    "CONROLE SAO PAULO",
    "20201129204251",
    "Sarasota Tower",
    "20201129204832",
    "KMIA ATIS INFO Y 2153Z",
    "New York Approach",
    "Ezeiza Radar",
    "Washington Center",
    "Ezeiza Ground",
    "KLAL ATIS INFORMATION R",
    "Cordoba Control",
    "Cordoba Control",
    "Binghamton Approach",
    "KSRQ ATIS INFORMATION T",
    "Lima Control",
    "Toronto Centre",
    "20201129211132",
    "KMCO ATIS INFORMATION P",
    "KJAX ATIS INFO G 2156Z",
    "Toronto Arrival 132",
    "Torre Congonhas",
    "KIAD ATIS INFO G 2152Z",
    "Navy Key West Approach",
    "Check our UK area sectors here  https",
    "SBSP ATIS INFORMATION B",
    "Callsing Santiago Oceanico",
    "Lindbergh Ground on 123",
    "Liverpool Ground",
    "BOSTON LOGAN AIRPORT ATIS INFORMATION P",
    "Lisboa Control",
    "Miami Departure",
    "Ezeiza Tower",
    "KFLL ATIS INFORMATION W",
    "SBKP ATIS INFORMATION B",
    "KSFO ATIS INFORMATION D",
    "Moncton Centre",
    "Polaris Control Sector 4",
    "KSAN ATIS INFO L 2151Z",
    "Santiago Control Terrestre",
    "Baires Radar",
    "20201129221905",
    "CYYZ ATIS INFORMATION J",
    "Thanks for flying with the Winnipeg FIR",
    "WINNIPEG INTERNATIONAL",
    "Vancouver Tower",
    "Torre Fortaleza",
    "Torre Guarulhos",
    "KLAX ATIS INFO A 2153Z",
    "AUCKLAND INTERNATIONAL AIRPORT ATIS INFORMATION GOLF",
    "Moncton Center",
    "Bucharest Radar",
    "Lisboa Approach",
    "PINTO MARTINS INTERNATIONAL AIRPORT ATIS INFORMATION NOVEMBER",
    "New York Approach",
    "BRADLEY INTERNATIONAL AIRPORT ATIS INFORMATION I",
    "KJFK ATIS INFO T 2151Z",
    "KEWR ATIS INFO D 2151Z",
    "Cordoba Center",
    "KSEA ATIS INFO O 2153Z",
    "NOTAM",
    "SBGR ATIS INFORMATION I",
    "Wien Tower",
    "Kastrup Tower",
    "Bruno Veiga",
    "Christchurch Control",
    "WELLINGTON INFORMATION FOXTROT",
    "Vancouver Ground",
    "Santo Domingo Control",
    "Havana Center",
    "Kennedy Ground",
    "Orlando East Approach",
    "TENERIFE SUR TOWER",
    "Muenchen Radar",
    "KPBI ARR",
    "ARTURO MERINO BENITE AIRPORT ATIS INFORMATION QUEBEC",
    "Aeroparque Tower",
    "Perfect Tower",
    "Torre"
}
return allConvertedNames
